version: '3.0'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: development
    ports:
      - "${PORT}:4000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    restart: on-failure
    depends_on:
      - prisma
    networks:
      - rss-network
  prisma:
    image: node:lts-alpine
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npx prisma migrate dev"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    depends_on:
      - db
    networks:
      - rss-network
  db:
    build:
      context: .
      dockerfile: Dockerfile.database
    ports:
      - "5432:5432"
    volumes:
      - postgres_artifacts:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: on-failure
    networks:
      - rss-network

networks:
  rss-network:
    driver: bridge

volumes:
  postgres_artifacts: